### PR TITLE
Fix regression breaking Into/Convert node type coercion

### LINKED ISSUE #3677: Convert node no longer supports strings
A regression introduced by @Keavon in #3662.

Previously you could connect a number to the text (create text with text tool, open node graph, select text node, click dot next to text input)
<img width="935" height="208" alt="working number -> text" src="https://github.com/user-attachments/assets/a02ea56b-e9ce-4ff2-a09f-49a4283c5855" />

Now it doesn't work:

error

```
This input type is incompatible:
• Input 2:
…found:       f64 called with Context
…expected: string called with Context
```

The name of the `String` type is now for some reason changed:
https://github.com/GraphiteEditor/Graphite/blob/7af60e02a33a4fa22edc058d57021ced5d8d63eb/node-graph/libraries/core-types/src/types.rs#L389-L391

So no convert node is found to match it:
https://github.com/GraphiteEditor/Graphite/blob/7af60e02a33a4fa22edc058d57021ced5d8d63eb/node-graph/preprocessor/src/lib.rs#L72-L84

### PR DESCRIPTION
**Pull request by Keavon**
Fixes a regression from #3662. Closes #3677.

This also refactors some code messiness around how we did `Display` vs. `Debug` printing of type representations.

### CODE REVIEW

File: node-graph/libraries/core-types/src/types.rs [hunk 1]
```diff
@@ -337,15 +336,17 @@ impl Type {
 		}
 	}
 
-	pub fn to_cow_string(&self) -> Cow<'static, str> {
+	pub fn identifier_name(&self) -> String {
```
Comment (TrueDoctor) [inline node-graph/libraries/core-types/src/types.rs:339]: What is the reason for the changed return type here?

Comment (Keavon) [reply node-graph/libraries/core-types/src/types.rs:339]: This isn't a change, one unused function is deleted and another new function is added in the same location.
