### PR TITLE
Fix Pen tool anchor point overlays disappearing forever after viewing the node graph

### LINKED ISSUE #3505: The Pen tool doesn't show overlays for anchors, after the node graph has been opened
This is a regression that was introduced back in @4adex's #3070. It's been bothering me but I haven't been able to find how to reproduce it until now. Thankfully it's an easy reproduction: just open and close the node graph, then afterwards, the Pen tool will have permanently lost its ability to display anchor point overlay squares.

https://github.com/user-attachments/assets/26de1e6e-497f-450d-b548-97df680c0512

### PR DESCRIPTION
**Pull request by Annonnymmousss**
@Keavon please review this
fixed the issue of pen tool loosing its ability to produce anchor points after open/close of node graph

https://github.com/user-attachments/assets/1b67bbdd-9445-4dca-8335-0e746f88c9c3

Closes #3505

### CODE REVIEW

File: editor/src/messages/portfolio/document/overlays/utility_functions.rs [hunk 1]
```diff
@@ -135,14 +135,13 @@ pub fn path_overlays(document: &DocumentMessageHandler, draw_handles: DrawHandle
...
-		let Some(selected_shape_state) = shape_editor.selected_shape_state.get_mut(&layer) else {
-			continue;
-		};
-
+		let selected_shape_state = shape_editor.selected_shape_state.entry(layer).or_default();
 		// Get the selected segments and then add a bold line overlay on them
-		for (segment_id, bezier, _, _) in vector.segment_iter() {
-			if selected_shape_state.is_segment_selected(segment_id) {
-				overlay_context.outline_select_bezier(bezier, transform);
+		if !selected_shape_state.selected_points().collect::<Vec<_>>().is_empty() {
```
Comment (0HyperCube) [inline editor/src/messages/portfolio/document/overlays/utility_functions.rs]: There is no need to do `collect`. Memory allocation is expensive and isn't needed. You can just do `selected_shape_state.selected_points().next().is_some()`.

**Comment by Annonnymmousss** [comment]
@0HyperCube done with changes
thankyou for guiding

File: editor/src/messages/portfolio/document/overlays/utility_functions.rs [hunk 2]
```diff
@@ -135,14 +135,13 @@ pub fn path_overlays(document: &DocumentMessageHandler, draw_handles: DrawHandle
...
-		let Some(selected_shape_state) = shape_editor.selected_shape_state.get_mut(&layer) else {
-			continue;
-		};
-
+		let selected_shape_state = shape_editor.selected_shape_state.entry(layer).or_default();
 		// Get the selected segments and then add a bold line overlay on them
-		for (segment_id, bezier, _, _) in vector.segment_iter() {
-			if selected_shape_state.is_segment_selected(segment_id) {
-				overlay_context.outline_select_bezier(bezier, transform);
+		if selected_shape_state.selected_points().next().is_some() {
```
Comment (4adex) [inline editor/src/messages/portfolio/document/overlays/utility_functions.rs]: This if statement is irrelevant in context to this issue. Is there some specific reason to add it here? The issue is already solved by eliminating `continue` in line 138 which was earlier preventing drawing overlays when `selected_shape_state` was `None`.

Comment (Keavon) [reply editor/src/messages/portfolio/document/overlays/utility_functions.rs]: @4adex please feel free to submit a separate PR if you know a better solution (i.e. don't let the existence of one PR make you hesitate from opening your own, since we merge PRs based on what's the best outcome for the codebase).

Comment (Annonnymmousss) [reply editor/src/messages/portfolio/document/overlays/utility_functions.rs]: okay the issue is solved just by removing the continue statement..
the if condition is redundant here..

Comment (4adex) [reply editor/src/messages/portfolio/document/overlays/utility_functions.rs]: @Keavon this PR fixes the issue now, LGTM.

Comment (Keavon) [reply editor/src/messages/portfolio/document/overlays/utility_functions.rs]: Ok, thanks for looking. Please give an approval through GitHub if you have a second.

**Review by 4adex — APPROVED** [review]

**Comment by Keavon** [comment]
!build

**Review by Keavon — APPROVED** [review]

**Comment by Keavon** [comment]
Thanks. Please comment in the issue.
