### PR TITLE
Fix fill tool on raster image temporarily breaks the graph

### LINKED ISSUE #2270: Using fill tool on a raster layer temporarily breaks the graph
To reproduce:
- Paste a raster image
- Select the fill tool
- Click on the image
- Observe that the node graph has an error since the fill node does not support the raster input.

Since the tooling should avoid breaking the graph as part of #2214.

### PR DESCRIPTION
**Pull request by EllenGYY**
Closes #2270 

Detect whether the current layer is backed by a raster image. If it is, avoid calling the vector fill function to prevent temporarily breaking the graph.

### CODE REVIEW

File: editor/src/messages/tool/common_functionality/graph_modification_utils.rs [hunk 1]
```diff
@@ -417,4 +417,19 @@ impl<'a> NodeGraphLayer<'a> {
...
 	}
+
+	// Check if the current layer is backed by a raster image
+	pub fn is_raster_image(layer: LayerNodeIdentifier, network_interface: &NodeNetworkInterface) -> bool {
+		// Create a NodeGraphLayer instance with the layer node identifier
+		let layer = NodeGraphLayer::new(layer, network_interface);
+		// Get the last node in the layer's flow and check if it is a raster image
+		if let Some(node_id) = layer.horizontal_layer_flow().last() {
+			let node_name = network_interface.frontend_display_name(&node_id, &[]);
+			if let Some(TaggedValue::ImageFrame(_)) = layer.find_input(&node_name, 1) {
```
Comment (0HyperCube) [inline editor/src/messages/tool/common_functionality/graph_modification_utils.rs:428]: This isn't a particularly robust approach as nodes can produce raster data without an image frame input. For example the noise pattern node (if it wasn't broken).

Comment (EllenGYY) [reply editor/src/messages/tool/common_functionality/graph_modification_utils.rs]: I change it to checking the document node definition catogory for now. As long as the catogory is correctly maintained when adding new nodes it should work fine. The noise pattern node is broken as mentioned in #2397.

Comment (0HyperCube) [reply editor/src/messages/tool/common_functionality/graph_modification_utils.rs]: @EllenGYY Would it perhaps be better to check the actual input type?
```rs
let layer_input_type = self.network_interface.input_type(&InputConnector::node(layer.to_node(), 1), &[]).0.nested_type();
layer_input_type == concrete!(graphene_std::RasterFrame)
```

Comment (EllenGYY) [reply editor/src/messages/tool/common_functionality/graph_modification_utils.rs]: Done. Currently I use soemthing similar to this `Some(x) if x == TypeId::of::<RasterFrame>() || x == TypeId::of::<ImageFrameTable<Color>>() || x == TypeId::of::<TextureFrameTable>() ` to check for the three raster types, since the input type is not wrapped in a RasterFrame.

**Review by 0HyperCube — APPROVED** [review]
Works well; thanks for the contribution.

I think that checking the types is the best approach as it deals with cases such as the conversion of raster->vector with #2332. Thanks for your patience working through that.
