### PR TITLE
Ignore out-of-range mouse button values using from_bits_truncate

### LINKED ISSUE #3521: Crash when receiving pen-tablet input event
Editor panicked when reciving a pen Tablet eraser Input Event.
Reproducible and consistant.

```txt
panicked at editor/src/messages/input_mapper/utility_types/input_mouse.rs:107:53:
Invalid decoding of MouseKeys

Wp/<@https://editor.graphite.art/assets/index-BPxHMP7l.js:988:1384
w@https://editor.graphite.art/assets/index-BPxHMP7l.js:970:73924
handleJsMessage@https://editor.graphite.art/assets/index-BPxHMP7l.js:970:74072
yp/e<@https://editor.graphite.art/assets/index-BPxHMP7l.js:970:74496
ep/o.wbg.__wbg_call_833bed5770ea2041/<@https://editor.graphite.art/assets/index-BPxHMP7l.js:970:14904
Ke@https://editor.graphite.art/assets/index-BPxHMP7l.js:969:6188
ep/o.wbg.__wbg_call_833bed5770ea2041@https://editor.graphite.art/assets/index-BPxHMP7l.js:970:14874
graphite_wasm.wasm._ZN13graphite_wasm10editor_api12EditorHandle27send_frontend_message_to_js17hb921190d4deab3e4E@https://editor.graphite.art/assets/graphite_wasm_bg-BjpNRPYb.wasm:wasm-function[807]:0x44c00d
graphite_wasm.wasm._ZN4core3ops8function2Fn4call17hce3f3ec565af54aaE@https://editor.graphite.art/assets/graphite_wasm_bg-BjpNRPYb.wasm:wasm-function[19280]:0xe83259
graphite_wasm.wasm._ZN3std9panicking20rust_panic_with_hook17he3dc6abfb01fb415E@https://editor.graphite.art/assets/graphite_wasm_bg-BjpNRPYb.wasm:wasm-function[10755]:0xd5f456
graphite_wasm.wasm._ZN4core9panicking9panic_fmt17h808dbde205a89691E@https://editor.graphite.art/assets/graphite_wasm_bg-BjpNRPYb.wasm:wasm-function[15108]:0xdfddfe
graphite_wasm.wasm._ZN4core6option13expect_failed17hb1784cfc9624364fE@https://editor.graphite.art/assets/graphite_wasm_bg-BjpNRPYb.wasm:wasm-function[12883]:0xdd1ef0
graphite_wasm.wasm._ZN15graphite_editor8messages12input_mapper13utility_types11input_mouse16EditorMouseState29from_keys_and_editor_position17hed9f2b202a6d4531E@https://editor.graphite.art/assets/graphite_wasm_bg-BjpNRPYb.wasm:wasm-function[13273]:0xddb253
graphite_wasm.wasm.editorhandle_onMouseMove@https://editor.graphite.art/assets/graphite_wasm_bg-BjpNRPYb.wasm:wasm-function[6150]:0xbb7f5e
onMouseMove@https://editor.graphite.art/assets/index-BPxHMP7l.js:970:7966
T@https://editor.graphite.art/assets/index-BPxHMP7l.js:977:2969
action@https://editor.graphite.art/assets/index-BPxHMP7l.js:977:727
```

### PR DESCRIPTION
**Pull request by Ayush2k02**
Have'nt tested this locally since I don't have a tablet on me . But like [0HyperCube](https://github.com/0HyperCube) suggested, using the from_bits_truncate here . Don't see any other or better approach to this as well

Closes #3521

### CODE REVIEW

**Comment by Ayush2k02** [comment]
Any updates on this !

**Comment by Keavon** [comment]
Not yet, still working to get caught up on PR reviews. Don't let this block you in other threads of work you're interested in, though!

File: editor/src/messages/input_mapper/utility_types/input_mouse.rs [hunk 1]
```diff
@@ -76,7 +76,7 @@ pub struct EditorMouseState {
 
 impl EditorMouseState {
 	pub fn from_keys_and_editor_position(keys: u8, editor_position: EditorPosition) -> Self {
-		let mouse_keys = MouseKeys::from_bits(keys).expect("Invalid decoding of MouseKeys");
+		let mouse_keys = MouseKeys::from_bits_truncate(keys);
```
Comment (TrueDoctor) [inline editor/src/messages/input_mapper/utility_types/input_mouse.rs:80]:
```suggestion
        // TODO: Some graphic tablets send key codes not mentioned in the spec. In the future we would like to support these as well.
		let mouse_keys = MouseKeys::from_bits_truncate(keys);
```
