### PR TITLE
Fix context menu blocking keyboard input after closing node graph

### LINKED ISSUE #3559: Not possible to remove an object while context menu is opened in the node graph
**Description:**
If open the context menu in the node graph view and then close the node graph view, then it is not possible to remove objects in the graphics area.
Curiously enough, if open node graph view again, the context menu is still opened. Is it intended behavior? Or will it be better to close the context menu when user closes the node graph view?

**Environment:**
The bug is happening in the desktop version of Graphite app (commit 9f25c50c) on MS Windows 11 Home (v10.0.26200).

**Steps to reproduce:**
1. Start the desktop of Graphite.
2. Create new document.
3. In the document, draw a rectangle.
4. Open the node graph view.
5. Right click in the node graph to open the context menu.
6. Close the node graph view without closing the context menu.
7. Select the rectangle in the graphics area and try to remove it by pressing the Del key.

Expected: the rectangle is removed
Actual: the rectangle is not removed

### PR DESCRIPTION
**Pull request by Ayush2k02**
BEFORE ( Nothing happens when the user click delete after the whole flow )

https://github.com/user-attachments/assets/487dec52-5121-434e-8ed4-f7c8ca52dfe1

AFTER ( Delete and other operations working now )

https://github.com/user-attachments/assets/56a2fac5-36fb-41ed-852e-dc82b3fe83f8

Simple enough fix which passes `nodegraph` to `createDocumentState` and call `closeContextMenu` when the user shifts to the artboard from node graph

Closes #3559

### CODE REVIEW

**Comment by Ayush2k02** [comment]
Any updates on this guys !

File: frontend/src/state-providers/document.ts [hunk 1]
```diff
@@ -79,6 +80,10 @@ export function createDocumentState(editor: Editor) {
 	editor.subscriptions.subscribeJsMessage(UpdateGraphViewOverlay, (data) => {
 		update((state) => {
 			state.graphViewOverlayOpen = data.open;
+			// Close the context menu when the graph view overlay is closed
+			if (!data.open && nodeGraph) {
+				nodeGraph.closeContextMenu();
+			}
```
Comment (Keavon) [inline frontend/src/state-providers/document.ts]:
```suggestion

			// Close the context menu when the graph view overlay is closed
			if (!data.open && nodeGraph) nodeGraph.closeContextMenu();

```

File: frontend/src/state-providers/document.ts [hunk 2]
```diff
@@ -79,6 +80,10 @@ export function createDocumentState(editor: Editor) {
 	editor.subscriptions.subscribeJsMessage(UpdateGraphViewOverlay, (data) => {
 		update((state) => {
 			state.graphViewOverlayOpen = data.open;
+
+			// Close the context menu when the graph view overlay is closed
+			if (!data.open && nodeGraph) nodeGraph.closeContextMenu();
```
Comment (Keavon) [inline frontend/src/state-providers/document.ts]: Mutating some external thing's state as a side effect of this thing's state update isn't appropriate.

**Comment by Ayush2k02** [comment]
Done , I believe this is what you meant @Keavon in this discord discussion here 
https://discord.com/channels/731730685944922173/1210129484255076354/1463109436326416384

**Comment by Ayush2k02** [comment]
https://github.com/user-attachments/assets/3dc8ecab-1700-4de2-8caa-87f2fa342301

**Comment by Ayush2k02** [comment]
Fixed the issue, this one is now good to review from my side

File: frontend/src/components/views/Graph.svelte [hunk 3]
```diff
@@ -20,12 +21,18 @@
...
 
 	let graph: HTMLDivElement | undefined;
 
 	$: gridSpacing = calculateGridSpacing($nodeGraph.transform.scale);
 	$: gridDotRadius = 1 + Math.floor($nodeGraph.transform.scale - 0.5 + 0.001) / 2;
 
+	// Close the context menu when the graph view overlay is closed
+	$: if (!$document.graphViewOverlayOpen) {
+		nodeGraph.closeContextMenu();
+	}
```
Comment (Keavon) [inline frontend/src/components/views/Graph.svelte]: One line please, since this is short enough.

Comment (Ayush2k02) [reply frontend/src/components/views/Graph.svelte]: Done !

**Comment by Keavon** [comment]
!build
