### PR TITLE
Desktop: Fix bitmap file export not preserving alpha

### LINKED ISSUE #3609: Transparency not preserved on desktop export [Linux]
Exporting images with Transparent enabled still gives them a white background.

Tested: Doesn't work on Appimage or Flatpak, but works fine on [latest](https://dev.graphite.art).  
KDE 6.5 with Wayland on Fedora 43.

### PR DESCRIPTION
**Pull request by timon-schelling**
Closes #3609

### CODE REVIEW

File: node-graph/libraries/wgpu-executor/src/lib.rs [hunk 1]
```diff
@@ -98,7 +98,7 @@ impl WgpuExecutor {
 			output.as_mut().unwrap()
 		};
 
-		let [r, g, b, a] = background.to_rgba8_srgb();
```
Comment (TrueDoctor) [inline node-graph/libraries/wgpu-executor/src/lib.rs]: Does this change anything regarding the functionality or is this an unrelated api restructure

Comment (timon-schelling) [reply node-graph/libraries/wgpu-executor/src/lib.rs]: API restructure to make desktop wrapper etc. not depend on graphene Color.
