### PR TITLE
Fix panic dialogue when handling a message

### LINKED ISSUE #574: The editor sometimes panics without displaying a crash dialog

### PR DESCRIPTION
**Pull request by 0HyperCube**
The crash dialogue is not triggered when a panic happens when handling a message because the `instances` refcell is borrowed and so cannot be borrowed again in order to get the `JsEditorHandle` and display the dialogue. This caused the panic handler to panic.

This MR splits `JsEditorHandle`s and rust `Editor`s into separate refcells to fix this (testable currently by pressing delete while drawing with pen tool).

Fixes #574

### CODE REVIEW

**Review by Keavon — APPROVED** [review]
Elegant fix, thank you for investigating this!

File: frontend/src/lifetime/errors.ts [hunk 1]
```diff
@@ -71,12 +71,11 @@ function githubUrl(panicDetails: string): string {
...
-		Copied from the crash dialog in the Graphite Editor:
+		Copied from the crash dialog in the Graphite Editor:`;
 
-		\`\`\`
-		${panicDetails}
-		\`\`\`
-		`;
+	body += "\n\n```\n";
+	body += panicDetails;
+	body += "```";
```
Comment (Keavon) [inline frontend/src/lifetime/errors.ts:78]: Missing a `\n` between `panicDetails` and the three backticks.

File: frontend/src/lifetime/errors.ts [hunk 2]
```diff
@@ -71,12 +71,11 @@ function githubUrl(panicDetails: string): string {
 		${browserVersion()}, ${operatingSystem()}
 
 		**Stack Trace**
-		Copied from the crash dialog in the Graphite Editor:
+		Copied from the crash dialog in the Graphite Editor:`;
```
Comment (Keavon) [inline frontend/src/lifetime/errors.ts:74]: It's slightly stylistically preferable to put the closing backtick on the next line. I think that also means you can avoid the double `\n` on the next concatenation.

File: frontend/src/lifetime/errors.ts (hunk 1 above)
Comment (0HyperCube) [reply frontend/src/lifetime/errors.ts:78]: panicDetails has a trailing `\n`

File: frontend/src/lifetime/errors.ts (hunk 2 above)
Comment (0HyperCube) [reply frontend/src/lifetime/errors.ts:74]: You do trim.

File: frontend/src/lifetime/errors.ts (hunk 1 above)
Comment (Keavon) [reply frontend/src/lifetime/errors.ts:78]: Maybe we should `.trim()` `panicDetails` then and manually add the `\n` if there's ever inconsistency. Maybe it's even browser-dependent. This is on Chrome.

File: frontend/src/lifetime/errors.ts (hunk 2 above)
Comment (Keavon) [reply frontend/src/lifetime/errors.ts:74]: Gotcha, no worries then.

File: frontend/src/lifetime/errors.ts (hunk 1 above)
Comment (0HyperCube) [reply frontend/src/lifetime/errors.ts:78]: It does appear to be browser dependant.

**Comment by Keavon** [comment]
Looks perfect now! Ready to merge when CI finishes.
