### PR TITLE
Fix non-default gradient rendering with Vello

### LINKED ISSUE #1864: Fix Vello not rendering non-default gradients
Gradients currently break as soon as they are edited using the gradient tool. This is likely a transform issue

### PR DESCRIPTION
**Pull request by TrueDoctor**
Closes #1864 , #1866 , #1867

### CODE REVIEW

File: node-graph/gcore/src/graphic_element/renderer.rs [hunk 1]
```diff
@@ -377,7 +377,7 @@ impl GraphicElementRendered for VectorData {
 				let start = lerp_bounds(gradient.start);
 				let end = lerp_bounds(gradient.end);
 
-				let transform = self.transform * gradient.transform;
+				let transform = self.transform /* * gradient.transform*/;
 				let start = transform.transform_point2(start);
 				let end = transform.transform_point2(end);
```
Comment (Keavon) [inline node-graph/gcore/src/graphic_element/renderer.rs:382]:
```suggestion
				let start = self.transform.transform_point2(start);
				let end = self.transform.transform_point2(end);
```

**Review by Keavon — APPROVED** [review]
