### PR TITLE
Fix noise pattern parameter issue

### LINKED ISSUE #2397: Noise Pattern node is broken
i cant get the noise pattern node to work. it looks like it expects more inputs than there are in the properties panel.
(there is only one boolean input in the properties panel )

this is a bug, right? 
or am i using it wrong?

error message:

This node isn't compatible with the com-
bination of types for the data it is given:
• Input 1: () → bool          
• Input 2: () → bool
• Input 3: () → u32
• Input 4: () → f64
• Input 5: () → NoiseType
• Input 6: () → DomainWarpType
• Input 7: () → f64
• Input 8: () → FractalType
• Input 9: () → u32
• Input 10: () → f64
• Input 11: () → f64
• Input 12: () → f64
• Input 13: () → f64
• Input 14: () → CellularDistanceFunction
• Input 15: () → CellularReturnType
• Input 16: () → f64

Each invalid input should be replaced by
data with one of these supported types:
• Input 1: () → ()

### PR DESCRIPTION
**Pull request by EllenGYY**
Closes #2397 

A small bug in the node definition parameter causes the issue. Now fixed.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -4,3 +4,6 @@ target/
 perf.data*
 profile.json
 flamegraph.svg
+
+.cursor/
+.vscode/
```
Comment (Keavon) [inline .gitignore:9]: Please revert this file change.

File: editor/src/messages/portfolio/document/node_graph/document_node_definitions.rs [hunk 2]
```diff
@@ -727,7 +727,8 @@ fn static_nodes() -> Vec<DocumentNodeDefinition> {
 					manual_composition: Some(concrete!(Context)),
 					implementation: DocumentNodeImplementation::ProtoNode(ProtoNodeIdentifier::new("graphene_std::raster::NoisePatternNode")),
 					inputs: vec![
-						NodeInput::value(TaggedValue::Bool(false), false),
+						NodeInput::value(TaggedValue::None, false),
+						// NodeInput::value(TaggedValue::Bool(false), false),
```
Comment (Keavon) [inline editor/src/messages/portfolio/document/node_graph/document_node_definitions.rs:731]: We don't like to commit commented out lines unless there's a specific reason they will be needed in the future, usually with a TODO comment note about what it's for.

File: .gitignore (hunk 1 above)
Comment (EllenGYY) [reply .gitignore]: fixed

File: editor/src/messages/portfolio/document/node_graph/document_node_definitions.rs (hunk 2 above)
Comment (EllenGYY) [reply editor/src/messages/portfolio/document/node_graph/document_node_definitions.rs]: fixed

**Review by 0HyperCube — APPROVED** [review]
Thanks for this fix @EllenGYY.
