### PR TITLE
Fix text layer getting deselected after clicking out of Text tool interactive editing

### LINKED ISSUE #2127: Keep selection when clicking in properties after creating text
- Create a new text box
- Type something
- Attempt to modify something in the properties of the newly added text layer (e.g. change the fill colour)
- The layer is deselected so the properties disappear.

It would be nice to keep the properties around when the user is trying to edit them.

### PR DESCRIPTION
**Pull request by Sidharth-Singh10**
Closes #2127

- Introduced the `active_panel` field in `DocumentMessageHandle`r to track the currently active interface panel.
- Added a match expression in `set_editing` fn to verify if the active panel is the Properties Panel, preventing its deselection during edits.

https://github.com/user-attachments/assets/dd34f593-b3e0-4f54-b65a-f8cde3af87ff

### CODE REVIEW

**Review by 0HyperCube — APPROVED** [review]
Works well; thanks for this contribution.

**Comment by Keavon** [comment]
@adamgerhant could you please review this in regards to the introduced ActivePanel code, to make sure it doesn't conflict with your existing implementation of the related concept of the active panel used for showing whether the graph's subnetwork or Layers panel is active?

**Review by adamgerhant — CHANGES_REQUESTED** [review]
The active panel is currently being stored in the portfolio message handler. There is no need to store it in the document message handler.

**Comment by 0HyperCube** [comment]
@adamgerhant the text tool code can't access the portfolio message handler.

**Comment by adamgerhant** [comment]
It could be passed as a parameter, but I think it makes sense for the active panel to be stored on a per document basis instead of the entire portfolio/application. This means switching tabs will store independent active panel states. In this case the active panel should be removed from the portfolio message handler.

**Comment by adamgerhant** [comment]
Why not just leave the text layer as selected when editing ends?

**Comment by Sidharth-Singh10** [comment]
I haven't worked much with design tools much, but doesn't keeping text layers selected after editing deviates from standard design tool patterns where edits typically end in deselection.
Persistent selection might create risk for accidental modifications - users may unintentionally resize/move/style the text layer when they meant to work on something else.

In this implementation the layer while in editing is deselected when clicked anywhere else expect properties panel

**Review by adamgerhant — APPROVED** [review]

**Comment by Keavon** [comment]
@Sidharth-Singh10 I like where you're going with that thought process, although I believe for consistency with other drawing tools in Graphite, it would be best to keep it selected after clicking out. If you draw with any other tool like Rectangle or Ellipse, you'll notice if you look in the Layers panel, that layer remains selected after finishing drawing it. So it'd be best if the layer remains selected if you click anywhere in the viewport, or anywhere else in the UI, after interactively editing the text. Thanks :)

**Review by Keavon — CHANGES_REQUESTED** [review]
See my previous comment for the updated approach, thanks!

File: editor/src/messages/portfolio/document/document_message_handler.rs [hunk 1]
```diff
@@ -144,6 +144,7 @@ impl Default for DocumentMessageHandler {
 			graph_view_overlay_open: false,
 			snapping_state: SnappingState::default(),
 			graph_fade_artwork_percentage: 80.,
+
```
Comment (Keavon) [inline editor/src/messages/portfolio/document/document_message_handler.rs:147]:
```suggestion
```

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
Can I have you add another little improvement to this PR while I'm thinking about it? If the user is editing the interactive text in the viewport, and hits escape, it should delete the entire text layer if escape was pressed when the text was empty. So if a user creates text in the wrong spot but doesn't type anything (or types then deletes it all), escape will delete the layer so it doesn't get invisibly stuck behind.

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
It looks like <kbd>Escape</kbd> is working but right-click isn't for canceling an empty text layer for it to get deleted. Can you please look into making it work when it's empty and the user right-clicks?

(Also note that I rebased, so you'll need to pull before continuing to code on it.)

**Comment by Sidharth-Singh10** [comment]
Hey @Keavon, I added an entry for `MouseRight` with `action_dispatch` set to `TextToolMessage::CommitText` in `input_mapping.rs`, but it doesn't seem to have any effect.

To confirm I was editing the correct location, I commented out the `MouseLeft` entry with `action_dispatch` set to `TextToolMessage::Interact`. This prevented placing or editing text, which suggests my changes are indeed in the right place.

Could you nudge me in the right direction?

**Comment by Keavon** [comment]
I'll ping @0HyperCube to see if he can answer your question about that.

**Comment by 0HyperCube** [comment]
@Sidharth-Singh10 

The actions that are advertised to the input mapper system don't include the commit text when the text is not being edited:
```rs
fn actions(&self) -> ActionList {
	match self.fsm_state {
		TextToolFsmState::Ready => actions!(TextToolMessageDiscriminant;
			Interact,
		),
		TextToolFsmState::Editing => actions!(TextToolMessageDiscriminant;
			Interact,
			Abort,
			CommitText,
		),
	}
}
```

Any time any mouse button is pressed that is not inside the text input, `input.ts:175` sends `editor.handle.onChangeText` which sets editing to false.

**Comment by Sidharth-Singh10** [comment]
Thanks for pointing this out!

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
@Sidharth-Singh10 your solution to emulate an escape keypress from the frontend TS code is a hack that works but isn't very clean. Can you please take into account what Hypercube wrote and implement a solution in the backend Rust code? In other words, you need to have something run before the tool state leaves `Editing` and returns to `Ready` to check if that TS code he mentioned is causing it to return to `Ready`.

**Comment by Keavon** [comment]
!build

**Review by Keavon — APPROVED** [review]
