### PR TITLE
Desktop: Restart without UI acceleration when it fails on Linux

### LINKED ISSUE #3667: On desktop, automatically fall back to non-hardware accelerated UI on failure
If we don't get a texture back from CEF within the first second of launching (i.e. we're detecting the user is seeing a blank screen), we should restart the app and persist a preference for a non-hardware accelerated UI fallback.

When running in that compatibility mode, an IconButton should be added to the bottom right of the app beside the app name/version status, letting us know from a screenshot/screencast that it's running in compatibility mode. Clicking that icon will then relaunch the editor with the compatibility mode disabled, attempting to return to normal operation (but possibly failing and restarting again to return to compatibility mode).

This should help us gracefully deal with these compatibility issues, but we also need to work with users who are encountering these issues to find the root causes and aim to solve those.

### PR DESCRIPTION
**Pull request by timon-schelling**
Partly closes #3667

### CODE REVIEW

File: desktop/src/app.rs [hunk 1]
```diff
@@ -629,3 +651,8 @@ impl ApplicationHandler for App {
 		event_loop.set_control_flow(ControlFlow::WaitUntil(wait_until));
 	}
 }
+
+pub(crate) enum ExitReason {
+	Shutdown,
+	UiAccalerationFailure,
```
Comment (Keavon) [inline desktop/src/app.rs]: UiAccelerationFailure

File: desktop/src/lib.rs [hunk 2]
```diff
@@ -77,6 +77,10 @@ pub fn start() {
 
 	let (cef_view_info_sender, cef_view_info_receiver) = std::sync::mpsc::channel();
 
+	if cli.disable_ui_acceleration {
+		println!("UI acceleration is disabled");
```
Comment (TrueDoctor) [inline desktop/src/lib.rs:81]: should this be an `eprintln` ?

Comment (timon-schelling) [reply desktop/src/lib.rs:81]: more of an info that an error, so in my opinion no.
but this will only stay for a couple of weeks anyways (until rc4).

Comment (TrueDoctor) [reply desktop/src/lib.rs:81]: The question is more if it should be included if I pipe the output of graphite to a file, and I'd think it should probably not. E.g. the `dbg!` macro also outputs to stderr, and I would argue that is similar in nature

Comment (timon-schelling) [reply desktop/src/lib.rs:81]: Then we should also change the Available GPU lines? 
I would merge this and we can decide later for all similar cases, currently most stuff ends up in stdout.

Comment (TrueDoctor) [reply desktop/src/lib.rs:81]: yes, we should, from `man stderr`
> Under normal circumstances every UNIX program has three streams opened for it when
       it  starts  up,  one for input, one for output, and one for printing diagnostic or
       error messages.
