### PR TITLE
Fix rasterize node document leakage with hashmap and eq check

### LINKED ISSUE #3533: Rasterize node: the rasterized image is leaking from one document to another
**Description:**
When using the Rasterize node in multiple documents which are opened at the same time, a rasterized image produced by the Rasterize node in one document is shown in another document which also uses the Rasterize node.

**Environment:**
The bug is happening in the web version of Graphite (link https://dev.graphite.art, commit 4ab75c9c) opened in the Opera web browser (v125.0.5729.49) on MS Windows 11 Home (v10.0.26200).

**Steps to reproduce:**
1. Open the web version of Graphite at https://dev.graphite.art.
2. Create a new document.
3. In the document, draw a circle in the top-left corner of the document.
4. In the Properties panel, add the Rasterize node to the circle.
5. Create another document.
6. In that new document, draw a rectangle in the top-left corner of the document.
7. In the Properties panel, add the Rasterize node to the rectangle.

Expected: the rectangle is shown in the second document.
Actual: the circle from the first document is shown in the second document, instead of the rectangle.

### PR DESCRIPTION
**Pull request by Ayush2k02**
Second approach for fixing this bug . Will be tested and benchmarked against https://github.com/GraphiteEditor/Graphite/pull/3539 to see if this is better

Closes #3533

### CODE REVIEW

File: node-graph/libraries/rendering/src/renderer.rs [hunk 1]
```diff
@@ -60,6 +60,9 @@ pub struct SvgRender {
 	pub svg_defs: String,
 	pub transform: DAffine2,
 	pub image_data: Vec<(u64, Image<Color>)>,
+	/// HashMap for O(1) lookup: content_hash -> (id, full_image_for_collision_check)
+	/// Used in deduplicating images efficiently
+	image_lookup: HashMap<u64, Vec<(u64, Image<Color>)>>,
```
Comment (0HyperCube) [inline node-graph/libraries/rendering/src/renderer.rs]: This ends up storing the image data twice? I don't think that this is desirable since images can have large memory requirements.

Comment (Ayush2k02) [reply node-graph/libraries/rendering/src/renderer.rs]: hmnmn, think I'll have the map reference the vector

Comment (TrueDoctor) [reply node-graph/libraries/rendering/src/renderer.rs]: This won't be allowed due to rusts ownership rules, but you can store an `Arc<Vec<…>>` in both. But I'm a bit confused why you have to do this at all, I would expect that just storing `(u64, Image<Color>)` in a `HashSet` should be all that we need, right?  The hash set / hash map already implement the eq check on hash collisions

**Comment by TrueDoctor** [comment]
Alright, I've now pushed another suggestion. If the perf of this is acceptable, I think this is going to be the simplest solution which is hopefully also relatively easy to maintain. @0HyperCube thoughts?

File: node-graph/libraries/rendering/src/renderer.rs (hunk 1 above)
Comment (Ayush2k02) [reply node-graph/libraries/rendering/src/renderer.rs]: That makes total sense - was redundantly reimplementing what HashMap does automatically. One follow-up question though ,  went with the manual approach because I was trying to preserve source_node_id when available (to avoid regenerating IDs for existing images). Your solution generates new UUIDs on every HashMap miss , is the source node Id not relevant here ?

**Comment by Ayush2k02** [comment]
This is so much more cleaner , wow

File: node-graph/libraries/rendering/src/renderer.rs (hunk 1 above)
Comment (TrueDoctor) [reply node-graph/libraries/rendering/src/renderer.rs]: The image source is just cheaper to compute if it exists, but if it does not exist the code should behave the same way. If the source ids are the same, we know that the images will also be the same without having to check them. We could also extend this with a second hashmap from source_id to image id and always first try to find the source id in the source_id hashmap (if we have a source id) and if not look up the full image. That should give us optimal perf characteristics, but I think I still prefer this simpler solution if the perf is good enough

File: node-graph/libraries/rendering/src/renderer.rs [hunk 2]
```diff
@@ -1239,23 +1239,21 @@ impl Render for Table<Raster<CPU>> {
...
-					let mut image = image.data().clone();
-					image.map_pixels(|p| p.to_unassociated_alpha());
-					render.image_data.push((id, image));
-				}
+				let mut image_copy = image.clone();
+				image_copy.data_mut().map_pixels(|p| p.to_unassociated_alpha());
+				let id = match render.image_data.entry(image_copy.into_data()) {
+					std::collections::hash_map::Entry::Occupied(occupied_entry) => *occupied_entry.get(),
+					std::collections::hash_map::Entry::Vacant(vacant_entry) => *vacant_entry.insert(generate_uuid()),
+				};
```
Comment (0HyperCube) [inline node-graph/libraries/rendering/src/renderer.rs]: This is just [`or_insert_with`](https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.or_insert_with) I guess.

Comment (TrueDoctor) [reply node-graph/libraries/rendering/src/renderer.rs]: Yes, I originally had more code in the vacant branch, but now that that's gone we should be able to simplify this

**Comment by Ayush2k02** [comment]
Let me know if there is something which could be done from my side

**Comment by TrueDoctor** [comment]
@Ayush2k02 Could you incorporate hypercubes suggestion and replace the `match` with a call to `or_insert_with` ?

**Comment by Ayush2k02** [comment]
Okay, let me take a look

**Comment by Ayush2k02** [comment]
Done !

**Comment by Ayush2k02** [comment]
https://github.com/user-attachments/assets/4db056ea-0f3e-433c-9ddb-051f5e66b943

Some manual testing

**Comment by Ayush2k02** [comment]
Screenshot 2026-01-04 at 5 11 31 PM

YAY !
