### PR TITLE
Fix capacity overflow in offset path node

### LINKED ISSUE #3288: Kurbo capacity overflow with `Offset Path` node
To reproduce take this artwork

https://gist.github.com/timon-schelling/9be36b2d76010c94aed0f7169110b5a6

and add offset path like in the video

https://github.com/user-attachments/assets/3f924316-864d-4b6e-99ca-e1525581ad69

Editor crashes

Crash in web:
```
panicked at /var/lib/github-actions/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/kurbo-0.11.3/src/bezpath.rs:218:16:
capacity overflow

Wp/<@https://dev.graphite.rs/assets/index-D7AV1-LH.js:988:1384
w@https://dev.graphite.rs/assets/index-D7AV1-LH.js:970:74414
handleJsMessage@https://dev.graphite.rs/assets/index-D7AV1-LH.js:970:74562
yp/e<@https://dev.graphite.rs/assets/index-D7AV1-LH.js:970:74986
ep/o.wbg.__wbg_call_833bed5770ea2041/<@https://dev.graphite.rs/assets/index-D7AV1-LH.js:970:14910
Ke@https://dev.graphite.rs/assets/index-D7AV1-LH.js:969:6188
ep/o.wbg.__wbg_call_833bed5770ea2041@https://dev.graphite.rs/assets/index-D7AV1-LH.js:970:14880
graphite_wasm.wasm._ZN13graphite_wasm10editor_api12EditorHandle27send_frontend_message_to_js17h6b27ffe527a088afE@https://dev.graphite.rs/assets/graphite_wasm_bg-BL700cnB.wasm:wasm-function[811]:0x44258c
graphite_wasm.wasm._ZN4core3ops8function2Fn4call17h3561e79a900b6a95E@https://dev.graphite.rs/assets/graphite_wasm_bg-BL700cnB.wasm:wasm-function[19363]:0xec1982
graphite_wasm.wasm._ZN3std9panicking20rust_panic_with_hook17he3dc6abfb01fb415E@https://dev.graphite.rs/assets/graphite_wasm_bg-BL700cnB.wasm:wasm-function[10803]:0xd9cd9b
graphite_wasm.wasm._ZN4core9panicking9panic_fmt17h808dbde205a89691E@https://dev.graphite.rs/assets/graphite_wasm_bg-BL700cnB.wasm:wasm-function[15197]:0xe3c9a3
graphite_wasm.wasm._ZN5alloc7raw_vec12handle_error17h841edd28c2df25a2E@https://dev.graphite.rs/assets/graphite_wasm_bg-BL700cnB.wasm:wasm-function[15773]:0xe44ab1
graphite_wasm.wasm._ZN5alloc7raw_vec19RawVec$LT$T$C$A$GT$8grow_one17hafa0a8c84f7f7e01E@https://dev.graphite.rs/assets/graphite_wasm_bg-BL700cnB.wasm:wasm-function[9936]:0xd68bc3
...

```

### PR DESCRIPTION
**Pull request by ashishmohapatra240**
Fixes #3288

Prevents infinite recursion in `fit_to_bezpath` by:
- Filtering out degenerate cubic beziers
- Capping max segments at 10k to prevent capacity overflow

https://github.com/user-attachments/assets/48e6ed63-c3b7-424b-bc63-f660a845d26b

### CODE REVIEW

**Comment by TrueDoctor** [comment]
I don't love lowering of the accuracy, is that a necessary change?

**Comment by ashishmohapatra240** [comment]
i initially relaxed the accuracy from 1e-3 to 1e-2 thinking it would reduce recursion depth in fit_to_bezpath, reverted to 1e-3.

**Comment by ashishmohapatra240** [comment]
Hey, @TrueDoctor Let me know if this works!

File: node-graph/gcore/src/vector/algorithms/offset_subpath.rs [hunk 1]
```diff
@@ -19,15 +20,30 @@ pub fn offset_bezpath(bezpath: &BezPath, distance: f64, join: Join, miter_limit:
...
+
+			let fitted = kurbo::fit_to_bezpath(&cubic_offset, CUBIC_TO_BEZPATH_ACCURACY);
+
+			if fitted.segments().count() > MAX_FITTED_SEGMENTS {
+				None
+			} else if fitted.get_seg(1).is_some() {
+				Some(fitted)
+			} else {
+				None
+			}
```
Comment (TrueDoctor) [inline node-graph/gcore/src/vector/algorithms/offset_subpath.rs]: This can be simplified by just returning `fitted.get_seg(1)`

Comment (TrueDoctor) [reply node-graph/gcore/src/vector/algorithms/offset_subpath.rs]: Ah, nevermind, it would need to be `fitted.get_seg(1).is_some().then_some(fitted)`

Comment (TrueDoctor) [reply node-graph/gcore/src/vector/algorithms/offset_subpath.rs]: Not sure if `fitted.get_seg(1).map(|_|fitted)` would work

**Comment by ashishmohapatra240** [comment]
simplified with `then_some()!`, much cleaner!

File: node-graph/gcore/src/vector/algorithms/offset_subpath.rs [hunk 2]
```diff
@@ -19,15 +20,28 @@ pub fn offset_bezpath(bezpath: &BezPath, distance: f64, join: Join, miter_limit:
...
-				kurbo::fit_to_bezpath(&cubic_offset, CUBIC_TO_BEZPATH_ACCURACY)
-			})
-			.filter(|bezpath| bezpath.get_seg(1).is_some()) // In some cases the reduced and scaled bézier is marked by is_point (so the subpath is empty).
-			.collect::<Vec<BezPath>>();
+		.segments()
+		.map(|bezier| bezier.to_cubic())
+		.filter_map(|cubic_bez| {
+			let start = cubic_bez.p0;
+			let is_degenerate =
+				(cubic_bez.p1 - start).hypot() < MAX_ABSOLUTE_DIFFERENCE && (cubic_bez.p2 - start).hypot() < MAX_ABSOLUTE_DIFFERENCE && (cubic_bez.p3 - start).hypot() < MAX_ABSOLUTE_DIFFERENCE;
```
Comment (TrueDoctor) [inline node-graph/gcore/src/vector/algorithms/offset_subpath.rs]: Could you add a quick comment about when this is true and why we return None in those cases? Also could you use `start.distance(cubic_bez.p1)` instead to make this more readable? If we introduced a squared constant, we could also use `start.distance_squared(cubic_bez.p1)` which would avoid the cost of computing the square root

Comment (ashishmohapatra240) [reply node-graph/gcore/src/vector/algorithms/offset_subpath.rs]: added comment explaining degenerate curves and switched to distance_squared(), please check.

**Review by TrueDoctor — APPROVED** [review]
Alright, looking good!
