### PR TITLE
Fix shape not closed after using Fill Tool

### LINKED ISSUE #509: Allow a filled polyline to be a draggable shape
Currently if you give a fill to a polyline (from the Pen Tool or Freehand Tool), you can only drag the line but can't drag the filled portion of the shape.

### PR DESCRIPTION
**Pull request by pkupper**
Closes #509
Well that was simpler than expected. @Keavon Let me know if the shape outline should be closed as well when using the fill tool.

### CODE REVIEW

**Comment by Keavon** [comment]
Somehow the click target is now actually the filled shape, and I can't see any obvious shape it's forming. In this video, every time I move my mouse I click afterwards showing that I'm often not clicking the shape's click target at all.

https://files.keavon.com/-/TriangularRedNutria/capture_3_.mp4

File: graphene/src/document.rs [hunk 1]
```diff
@@ -699,7 +699,10 @@ impl Document {
 			Operation::SetLayerFill { path, color } => {
 				let layer = self.layer_mut(path)?;
 				match &mut layer.data {
-					LayerDataType::Shape(s) => s.style.set_fill(layers::style::Fill::new(*color)),
+					LayerDataType::Shape(s) => {
+						s.style.set_fill(layers::style::Fill::new(*color));
+						s.closed = true;
```
Comment (Keavon) [inline graphene/src/document.rs:704]: I'm surprised this isn't causing the stroke to be drawn from the starting point to the ending point, since I thought that was what the `closed` property meant. However we don't actually want to change the stroke when filling the shape, since the shape is still open and it just happens to have a fill. Perhaps this `closed` property does what we want but it might be deserving of a rename. Pining @otdavies for thoughts.

Comment (pkupper) [reply graphene/src/document.rs:704]: Whether the path is closed is determined by whether or not the `kurbo::BezPath` ends with a `ClosePath` element. This closed field is only used for selection and should probably be called something like `solid` instead.

Comment (Keavon) [reply graphene/src/document.rs:704]: `filled` would probably be clearest, although couldn't we just remove the field entirely and check for whether it has a `Some(...)` or `None` fill color?

**Comment by pkupper** [comment]
> Somehow the click target is now actually the filled shape, and I can't see any obvious shape it's forming. In this video, every time I move my mouse I click afterwards showing that I'm often not clicking the shape's click target at all.
> 
> https://files.keavon.com/-/TriangularRedNutria/capture_3_.mp4

When I try to replicate the shape from the video I have the same issue. Strangely enough, for all other shapes I have tried it works just fine. Will investigate.

**Comment by Keavon** [comment]
> When I try to replicate the shape from the video I have the same issue. Strangely enough, for all other shapes I have tried it works just fine. Will investigate.

Indeed, it's pretty strange. Glad you're able to reproduce the problem and thank you for looking into it.

File: editor/src/document/document_message_handler.rs [hunk 2]
```diff
@@ -151,7 +151,7 @@ impl DocumentMessageHandler {
 			};
 
 			let (path, closed) = match &layer.ok()?.data {
-				LayerDataType::Shape(shape) => Some((shape.path.clone(), shape.closed)),
+				LayerDataType::Shape(shape) => Some((shape.path.clone(), shape.path.elements().last() == Some(&kurbo::PathEl::ClosePath))),
```
Comment (Keavon) [inline editor/src/document/document_message_handler.rs:154]: I thought the goal of removing `.closed` was to treat it as having a filled color, not something related to the Kurbo geometry?

Comment (pkupper) [reply editor/src/document/document_message_handler.rs:154]: The `closed` field was used incorrectly here. Probably due to the confusing naming. Here `closed` actually means whether the outline is closed. So the name fits.

Comment (Keavon) [reply editor/src/document/document_message_handler.rs:154]: Gotcha. Checking with @otdavies: does this cause any conflicts with your branch? And is this robust enough when multiple sub-shapes (separated by `moveto`s) are involved?

Comment (otdavies) [reply editor/src/document/document_message_handler.rs:154]: I will remove my usage of .closed and thus won't be an issue. I didn't use it before and I only recently incorporated it.

Comment (Keavon) [reply editor/src/document/document_message_handler.rs:154]: @pkupper: @otdavies and I discussed this and it sounds like the best course of action here is to put a comment above this line: `// TODO: This ClosePath check does not handle all cases, fix this soon` and then we can go ahead and merge your PR right away.

**Review by Keavon — APPROVED** [review]

**Review by otdavies — APPROVED** [review]
I don't see anything concerning here - I agree with these changes since it appears that closed was used incorrectly prior to these changes. Good work.

The TODO comment gives enough context to resolve in future situations.
