### PR TITLE
Fix n-gon Intersection

### LINKED ISSUE #302: Fix collision detection against N-gons
N-gons (created with the Shape Tool) do not have accurate collision detection. This is a problem for selecting such shapes with the Select Tool, filling it with the Fill Tool, and sampling its color with the Eyedropper Tool, among other problems. It's especially bad for lower values of N on the N-gons, like triangles.

### PR DESCRIPTION
**Pull request by pkupper**
Fixes intersection of n-gons by switching to our custom kurbo fork which adresses the following kurbo issue: https://github.com/linebender/kurbo/issues/180.

Also simplifies intersection logic through better use of kurbo.

Closes #302

---
This change is [Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/342)

### CODE REVIEW

**Review by Keavon — APPROVED** [review]

File: graphene/src/intersection.rs [hunk 1]
```diff
@@ -44,31 +54,17 @@ pub fn intersect_quad_bez_path(quad: Quad, shape: &BezPath, closed: bool) -> boo
...
-			}
-			if pos > 0 && neg > 0 {
-				return false;
-			}
-		}
+		// check if shape is entirely within the selection
+		return quad.path().contains(shape_point);
+	} else {
+		// empty shape
+		return false;
```
Comment (TrueDoctor) [inline graphene/src/intersection.rs:66]: you can remove the returns

Comment (pkupper) [reply graphene/src/intersection.rs]: Done

**Review by TrueDoctor — APPROVED** [review]
