### PR TITLE
Fix 'Shallow Select' mode behavior for selection context transference

### LINKED ISSUE #2392: Shallow Select mode fails to transfer selection to selected sibling
In the Select tool with *Shallow Select* mode set, I should be able to single-click the green shape in the viewport and transfer the selection to it, because it is the sibling of the already-selected layer. Currently it incorrectly selects the shared parent folder instead of the green shape's "Boolean Operation" layer if it's clicked. Clicking a layer within the same shared ancestor shouldn't return selection to being outside the scope of that shared ancestor.

Image

### PR DESCRIPTION
**Pull request by mTvare6**
Fixes #2392

### CODE REVIEW

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
!build

File: editor/src/messages/tool/tool_messages/select_tool.rs [hunk 1]
```diff
@@ -1590,16 +1645,47 @@ fn not_artboard(document: &DocumentMessageHandler) -> impl Fn(&LayerNodeIdentifi
...
+			.ancestors(metadata)
 			.filter(not_artboard(document))
-			.find(|&ancestor| document.network_interface.selected_nodes().selected_layers_contains(ancestor, document.metadata()));
+			.find(|&potential_lca| relevant_layers.iter().all(|layer| *layer == potential_lca || potential_lca.is_ancestor_of(metadata, layer)))
+			.and_then(|lca| {
+				let lca_children: Vec<_> = lca.children(metadata).collect();
+				(clicked_layer == lca)
+					.then_some(lca)
+					.or_else(|| lca_children.iter().find(|&&child| clicked_layer == child || child.is_ancestor_of(metadata, &clicked_layer)).copied())
+			})
```
Comment (Keavon) [inline editor/src/messages/tool/tool_messages/select_tool.rs:1677]: What does `lca` stand for? Expand this please.

**Comment by Keavon** [comment]
In Valley of Spires, if you click on anything except the sky (since that's not a group), it selects it. Then just single-click it again and it incorrectly deselects it.

File: editor/src/messages/tool/tool_messages/select_tool.rs (hunk 1 above)
Comment (mTvare6) [reply editor/src/messages/tool/tool_messages/select_tool.rs:1677]: Least common ancestor.

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
!build

**Comment by Keavon** [comment]
!build

**Review by Keavon — APPROVED** [review]
