### PR TITLE
Fix holding Ctrl in the graph not allowing for selecting nodes unless some are in a layer 

### LINKED ISSUE #3775: Holding Ctrl in the graph doesn't allow selecting nodes unless some are in a layer
Bug in the implementation of #3665.

https://github.com/user-attachments/assets/b37391a8-30f9-414f-9822-fd14a1596efb

@jsjgdh

### PR DESCRIPTION
**Pull request by jsjgdh**
Closes #3775

### CODE REVIEW

**Comment by Keavon** [comment]
!build ([build link](https://github.com/GraphiteEditor/Graphite/actions/runs/22086324186))

**Comment by Keavon** [comment]
!build ([build link](https://github.com/GraphiteEditor/Graphite/actions/runs/22087847599))

File: editor/src/messages/input_mapper/input_mappings.rs [hunk 1]
```diff
@@ -74,7 +74,7 @@ pub fn input_mappings(zoom_with_scroll: bool) -> Mapping {
 		entry!(KeyDown(MouseLeft); modifiers=[Alt], action_dispatch=NodeGraphMessage::PointerDown { shift_click: false, control_click: false, alt_click: true, right_click: false }),
 		entry!(KeyDown(MouseRight); action_dispatch=NodeGraphMessage::PointerDown { shift_click: false, control_click: false, alt_click: false, right_click: true }),
 		entry!(DoubleClick(MouseButton::Left); action_dispatch=NodeGraphMessage::EnterNestedNetwork),
-		entry!(PointerMove; refresh_keys=[Shift], action_dispatch=NodeGraphMessage::PointerMove { shift: Shift }),
+		entry!(PointerMove; refresh_keys=[Shift, Control, Alt], action_dispatch=NodeGraphMessage::PointerMove { shift: Shift }),
```
Comment (Keavon) [inline editor/src/messages/input_mapper/input_mappings.rs]:
```suggestion
		entry!(PointerMove; refresh_keys=[Control, Alt, Shift], action_dispatch=NodeGraphMessage::PointerMove { shift: Shift }),
```
