### PR TITLE
Fix snapping when drawing an artboard

### LINKED ISSUE #3263: While dragging a new Artboard only the starting point is snapped
When making new Artboard the starting point can be snapped to other objects in the document. But its no the case for the side that is actively dragged. In the screenshot below I was dragging the Artboard from top-left corner to the bottom and wanted for it to have the same height as the Artboard on the left:

Image

### PR DESCRIPTION
**Pull request by 0HyperCube**
Closes #3263

### CODE REVIEW

File: editor/src/messages/tool/tool_messages/artboard_tool.rs [hunk 1]
```diff
@@ -611,29 +611,61 @@ mod test_artboard {
...
+	impl ArtboardLayoutDocument {
+		pub fn new(position: impl Into<IVec2>, dimensions: impl Into<IVec2>) -> Self {
+			Self {
+				position: position.into(),
+				dimensions: dimensions.into(),
+			}
+		}
+	}
+
+	/// Check if all of the artboards exist in any ordering
```
Comment (TrueDoctor) [inline editor/src/messages/tool/tool_messages/artboard_tool.rs:628]: This could probably be simplified a bit by sorting the two vector but since this is a test this does not really matter

Comment (0HyperCube) [reply editor/src/messages/tool/tool_messages/artboard_tool.rs:628]: I think that implementing `Ord` for the artboards would be a bit confusing as it doesn't really have any semantic meaning.

Comment (TrueDoctor) [reply editor/src/messages/tool/tool_messages/artboard_tool.rs:628]: I mean, we could use `sort_by_key` to avoid having to implement `Ord` but we can just leave it as it is
