### PR TITLE
Fix box selection erroneously including zero-length handles; fix GRS failing on sharp points

### LINKED ISSUE #2534: GRS fails on sharp points and box selection wrongly targets its zero-length handles
*Temporarily claimed until April 11 by @4adex*

---

After dragging a corner point (not a smooth point) with the Path tool, hitting `V` to switch back to the Select tool, then hitting `G` for GRS works but `R` and `S` don't work, until you click somewhere to deselect the layer and click it again to reselect it.

Corner points that have been *clicked* to select fail, but *box selected* to select doesn't fail because it selects the zero-length handles as well as the anchor. We can see this by noticing how:
- Box selection of a single corner anchor makes it show
  
  Image

- As opposed to, when clicking
  
  Image

In this video, each mouse wiggle occurs after pressing `G` (of GRS):

https://github.com/user-attachments/assets/6b306093-4516-46cd-9e03-dbfadd0d695a

The symptoms described above are probably a pairing of two separate issues that both need to be fixed.

### PR DESCRIPTION
**Pull request by 4adex**
Closes #2534

### CODE REVIEW

**Comment by Keavon** [comment]
!build

File: editor/src/messages/tool/common_functionality/shape_editor.rs [hunk 1]
```diff
@@ -1444,7 +1444,14 @@ impl ShapeState {
 					if select {
 						match selection_change {
 							SelectionChange::Shrink => state.deselect_point(id),
-							_ => state.select_point(id),
+							_ => {
+								// select only those handles which are of non zero length
```
Comment (Keavon) [inline editor/src/messages/tool/common_functionality/shape_editor.rs:1448]:
```suggestion
								// Select only the handles which are of nonzero length
```

File: editor/src/messages/tool/transform_layer/transform_layer_message_handler.rs [hunk 2]
```diff
@@ -403,9 +403,12 @@ impl MessageHandler<TransformLayerMessage, TransformData<'_>> for TransformLayer
 							let handle1_length = handle1.length(&vector_data);
 							let handle2_length = handle2.length(&vector_data);
 
-							if (handle1_length == 0. && handle2_length == 0.) || (handle1_length == f64::MAX && handle2_length == f64::MAX) {
-								selected.original_transforms.clear();
-								return;
+							if (handle1_length == 0. && handle2_length == 0. && !using_select_tool) || (handle1_length == f64::MAX && handle2_length == f64::MAX && !using_select_tool) {
+								//G should work for such point but not R and S
```
Comment (Keavon) [inline editor/src/messages/tool/transform_layer/transform_layer_message_handler.rs:407]:
```suggestion
								// G should work for this point but not R and S
```

**Review by Keavon — APPROVED** [review]
