### PR TITLE
Move layer selection logic from vue to editor

### LINKED ISSUE #297: Move layer range selection logic to the Rust editor codebase
#137 added layer range selection in JS (using <kbd>Shift</kbd> and <kbd>Ctrl</kbd> modifier keys to expand a selection in the Layer Tree panel). See [LayerTree.vue](https://github.com/GraphiteEditor/Graphite/blob/master/frontend/src/components/panels/LayerTree.vue) for the `handleControlClick()`, `handleShiftClick()`, `handleClick()`, `deselectAllLayers()`, `fillSelectionRange()`, `clearSelection()`, and `sendSelectedLayers()` methods which pertain to this. Currently range selection mostly works (although there are bugs that can cause index out of bounds exceptions in JS), but it is very limited and buggy. Changing the list of layers (adding, duplicating, moving, etc.) causes problems with the selection context. Range selection will also need to work across folders. Another problem is that range selection does not preserve a shared context between layer selection in the Layer Tree panel and within the viewport. This shared context needs to understand which layer was most recently selected to know which range to expand from.

Another small detail is that <kbd>Shift</kbd> is the only modifier key used for range selection of layers in the viewport, since but <kbd>Ctrl</kbd> is also used in the Layer Tree panel. That's because the viewport only adds/removes layers from the selection while the Layer Tree does that and also does range selection from the recent selected layer context.

### PR DESCRIPTION
**Pull request by otdavies**
Closes #297

Future improvements when flattened data structure for layers is persisted:
* Remove reliance on layer_is_between(..)

---
This change is [Reviewable](https://reviewable.io/reviews/graphiteeditor/graphite/410)

### CODE REVIEW

File: frontend/wasm/src/api.rs [hunk 1]
```diff
@@ -306,6 +306,11 @@ impl Editor {
 		self.dispatch(message);
 	}
 
+	pub fn select_layer(&self, paths: Vec<LayerId>, ctrl: bool, shift: bool) {
```
Comment (TrueDoctor) [inline frontend/wasm/src/api.rs:309]: this does not look ffi safe, I would expect there to be an issue with bigints not being sendable across the js/rs boundary

Comment (otdavies) [reply frontend/wasm/src/api.rs:309]: This was how this was being done previous as far as I am aware. I just checked prior to my commit and similar examples seem to exist. Recommendations on how to proceed?

Comment (TrueDoctor) [reply frontend/wasm/src/api.rs:309]: Actually, nevermind, I think this could work: https://rustwasm.github.io/wasm-bindgen/reference/types/number-slices.html
(If not, we would have to turn paths into &[LayerId])
This just doesn't work for nested arrays

Comment (TrueDoctor) [reply frontend/wasm/src/api.rs:309]: The wasm-bindgen docs don't explicitly mention Vec as a supported type (or at least I didn't see it) but that might just be a lack of documentation

Comment (TrueDoctor) [reply frontend/wasm/src/api.rs:309]: You can leave it as it its I just got confused by the documentation

**Review by TrueDoctor — COMMENTED** [review]
I'll have to review this more thoroughly unfortunately didn't really have enough time today

**Comment by TrueDoctor** [comment]
This is definitely a change of behavior, when shift selecting layers, the point from where the selection starts is always kept the same, even if it is no longer selected, this seems a bit weird to me

**Comment by otdavies** [comment]
> 

I've attempted to copy window's behavior when it comes to selection. If it deviates from that, then that is unintended. In windows, if you continue to hold shift and click elsewhere it will _not_ choose a new start point for selection even if you deselect that folder with ctrl or deselect all together. 

If it doesn't behave correctly in that context, I want to immediately remedy that!

File: graphene/src/document.rs [hunk 2]
```diff
@@ -119,13 +120,60 @@ impl Document {
...
+
+			// If these are equal it means we are comparing folder elements
+			if a == b {
+				continue;
+			}
+
+			// If this is smaller, it is closer to the root
+			if a < b {
+				return true;
+			}
```
Comment (TrueDoctor) [inline graphene/src/document.rs:142]: I am not really sure how this makes sense, if the layer id is a uuid, the ordering of ids doesn't really make sense here.
the proper way would probably be to find the ordering in the corresponding folder

**Comment by TrueDoctor** [comment]
> > 
> 
> I've attempted to copy window's file explorer's behavior (by Keavon's request) when it comes to selection. If it deviates from that, then that is unintended. In window's file explorer, if you continue to hold shift and click elsewhere it will _not_ choose a new start point for selection even if you deselect that file/folder with ctrl or deselect all together.
> 
> If it doesn't behave correctly in that context, I want to immediately remedy that!

That seems to be the intended behaviour, we can probably still tweak the ux afterwards with something like a highlight for the last selected layer

**Comment by Keavon** [comment]
Please fix the behavior to match Windows Explorer. Namely, a <kbd>Ctrl</kbd> click should change the range selection reference layer.

File: graphene/src/document.rs (hunk 2 above)
Comment (otdavies) [reply graphene/src/document.rs:142]: The id here is the indices, not a UUID. Check the above lines.

**Comment by otdavies** [comment]
> Please fix the behavior to match Windows Explorer. Namely, a Ctrl click should change the range selection reference layer.

Done

File: graphene/src/document.rs (hunk 2 above)
Comment (otdavies) [reply graphene/src/document.rs]: I clarified the code / comments on this feedback, it would be confusing to anyone reading it.

Comment (TrueDoctor) [reply graphene/src/document.rs]: Thanks a lot, admittedly was pretty tired while reading the code but more comments are always welcome

File: graphene/src/document.rs [hunk 3]
```diff
@@ -119,13 +120,68 @@ impl Document {
...
+				// path_a is closer
+				return true;
+			}
+
+			// If neither of the above are true, path_b is closer
+			break;
+		}
+
+		// path_b is closer
+		return false;
```
Comment (TrueDoctor) [inline graphene/src/document.rs:154]: I was a bit confused by all the loop manipulation.
coldnt lines 144-154 just be replaced by
```rust
return index_a < index_b
```
? But i guess it makes sense in terms of putting comments inbetween

File: editor/src/document/document_file.rs [hunk 4]
```diff
@@ -568,6 +574,45 @@ impl MessageHandler<DocumentMessage, &InputPreprocessor> for DocumentMessageHand
...
+				let mut paths = vec![];
+				let last_selection_exists = !self.layer_range_selection_reference.is_empty();
+
+				// If we don't have ctrl selected, clear last selection
+				if !ctrl {
+					// Todo: This clears the selection, figure out how to improve this
+					self.layer_data.iter_mut().filter(|(_, layer_data)| layer_data.selected).for_each(|(path, layer_data)| {
+						layer_data.selected = false;
+						responses.push_back(LayerChanged(path.clone()).into())
+					});
```
Comment (TrueDoctor) [inline editor/src/document/document_file.rs:587]: responses.push_back(DeselectAllLayers.into());

File: editor/src/document/document_file.rs [hunk 5]
```diff
@@ -568,6 +574,45 @@ impl MessageHandler<DocumentMessage, &InputPreprocessor> for DocumentMessageHand
...
+						// This allows toggling selection when holding ctrl
+						let layer = self.layerdata_mut(&selected);
+						layer.selected = !layer.selected;
+						responses.push_back(LayerChanged(selected.clone()).into());
+					} else {
+						paths.push(selected.clone());
+					}
+
+					// Set our last selection reference
+					self.layer_range_selection_reference = selected;
```
Comment (TrueDoctor) [inline editor/src/document/document_file.rs:610]: I think this could probably be made a little bit simpler by using the existing messages for selection manipulition

**Review by TrueDoctor — APPROVED** [review]
@Keavon this is a preliminary approval. I've left some suggestions and would like Oliver to read through them before merging but it would be fine if it stayed as is

File: editor/src/document/document_file.rs (hunk 5 above)
Comment (otdavies) [reply editor/src/document/document_file.rs:610]: It does use the existing functions, just at the end when it has accumulated all the selection to be made..

File: graphene/src/document.rs (hunk 3 above)
Comment (otdavies) [reply graphene/src/document.rs:154]: I think this simplification is a good suggestion - it is like this due to breaking down the problem into simplified pieces in an earlier stage. Reconsolidating it now makes sense!

File: editor/src/document/document_file.rs (hunk 4 above)
Comment (otdavies) [reply editor/src/document/document_file.rs:587]: I would love this to work, but this is what I tried initially and it simply doesn't propagate the message in time it seems. It happens too late and deselects everything right after you select.

Comment (TrueDoctor) [reply editor/src/document/document_file.rs:587]: have you tried enabling the debug output to trace the messages?

Comment (TrueDoctor) [reply editor/src/document/document_file.rs:587]: Ah that is due to the push_front you did down there

**Comment by otdavies** [comment]
> @Keavon this is a preliminary approval. I've left some suggestions and would like Oliver to read through them before merging but it would be fine if it stayed as is

I've implemented the suggestions I could. I left some comments regarding why I couldn't implement them all.

I really appreciate all of your thoughtful review and guidance, thank you!

File: editor/src/document/document_file.rs (hunk 4 above)
Comment (otdavies) [reply editor/src/document/document_file.rs:588]: Oh, this one? _responses.push_front(AddSelectedLayers(paths).into());_. Let me try switching that around.

Comment (otdavies) [reply editor/src/document/document_file.rs:588]: I was following the structure of 
```
SetSelectedLayers(paths) => {
self.layer_data.iter_mut().filter(|(_, layer_data)| layer_data.selected).for_each(|(path, layer_data)| {
	layer_data.selected = false;
	responses.push_back(LayerChanged(path.clone()).into())
});

responses.push_front(AddSelectedLayers(paths).into());
}
```

Comment (otdavies) [reply editor/src/document/document_file.rs:588]: Hmm, I tried reordering the responses there. Making both push back, and other combinations with push front. The selection is somewhat functional when they both push back, but the shift select doesn't work properly. I'll investigate this more.

Comment (TrueDoctor) [reply editor/src/document/document_file.rs:588]: you can always press iirc `3` to open the message debugging (in the dev console) that should help to figure this out

Comment (otdavies) [reply editor/src/document/document_file.rs:588]: Resolved this issue by leaning on the function, _SetSelectedLayers_, that already has the clear logic, ha! 

```
// Add or set our selected layers
if ctrl {
	responses.push_front(AddSelectedLayers(paths).into());
} else {
	responses.push_front(SetSelectedLayers(paths).into());
}
```

As opposed to clearing before hand.

**Comment by TrueDoctor** [comment]
looks good to me

File: editor/src/document/document_file.rs [hunk 6]
```diff
@@ -601,11 +601,14 @@ impl MessageHandler<DocumentMessage, &InputPreprocessor> for DocumentMessageHand
 					self.layer_range_selection_reference = selected;
 				}
 
-				// Add or set our selected layers
-				if ctrl {
-					responses.push_front(AddSelectedLayers(paths).into());
-				} else {
-					responses.push_front(SetSelectedLayers(paths).into());
+				// Don't create messages for empty operations
```
Comment (otdavies) [inline editor/src/document/document_file.rs:604]: I realized, based on your astute suggestion @TrueDoctor, to monitor the messages with '3' + log,  that we were sending empty messages on occasion. Resolved that.
