### PR TITLE
Fix thumbnails not being updated for layers when they become empty

### LINKED ISSUE #3597: Groups not previewing correctly when empty
When I delete the last layer from an artboard or group, its preview stays as what it was before the deletion.

https://github.com/user-attachments/assets/0a93fd21-45b4-4e19-9e7b-e000619654cd

Issue exists on desktop (Linux) and web.

### PR DESCRIPTION
**Pull request by mohan-bee**
fixes #3597 

changed the handling of empty bounds (empty layers) from early returning to generate a empty svg and send to frontend.

before: 

https://github.com/user-attachments/assets/09f97443-35c5-4b4b-a3c9-779ccc3e419e

after fix: 

https://github.com/user-attachments/assets/0e8c3f99-a328-47f7-9a9d-97a322695273

### CODE REVIEW

File: editor/src/node_graph_executor/runtime.rs [hunk 1]
```diff
@@ -471,33 +471,39 @@ impl NodeRuntime {
...
-		let bounds = match graphic.bounding_box(DAffine2::IDENTITY, true) {
-			RenderBoundingBox::None => return,
-			RenderBoundingBox::Infinite => [DVec2::ZERO, DVec2::new(300., 200.)],
-			RenderBoundingBox::Rectangle(bounds) => bounds,
-		};
-		let footprint = Footprint {
-			transform: DAffine2::from_translation(DVec2::new(bounds[0].x, bounds[0].y)),
-			resolution: UVec2::new((bounds[1].x - bounds[0].x).abs() as u32, (bounds[1].y - bounds[0].y).abs() as u32),
-			quality: RenderQuality::Full,
+		// Get the bounds (as an Option)
```
Comment (adamgerhant) [inline editor/src/node_graph_executor/runtime.rs]: I don't think this comment or variable rename is necessary, but other than that it looks good.

**Comment by mohan-bee** [comment]
@adamgerhant  review pls !
