### PR TITLE
Move layouts definitions to backend and fix Firefox overlay scrollbars

### LINKED ISSUE #398: Fix overlaid scrollbars on Firefox
Since Firefox doesn't support the non-standard WebKit overlaid scrollbars CSS properties, and its "standard" API that it does support is terrible, the scrollbars end up displacing the content which breaks the layout, especially on horizontally scrolling content. I tried integrating the Overlay Scrollbars and Simplebar JS libraries but they do some crazy things to the DOM which massively breaks our styling. We might need a custom solution, or to use JS, or find some other workaround.

### LINKED ISSUE #646: Move Document Mode, Layer Tree panel's options bar, and tool shelf buttons from Vue to Rust
Currently these layouts are defined in Vue. Move them to the new backend system for layout definitions.

### PR DESCRIPTION
**Pull request by Keavon**
Closes #646
Closes #398

### CODE REVIEW

File: frontend/wasm/src/api.rs [hunk 1]
```diff
@@ -552,16 +488,13 @@ impl JsEditorHandle {
...
+		self.dispatch(message);
+		let message = ToolMessage::ActivateTool { tool_type: ToolType::Select };
 		self.dispatch(message);
-	}
-
-	// TODO(mfish33): Replace with initialization system Issue:#524
-	pub fn init_document_bar(&self) {
-		let message = PortfolioMessage::UpdateDocumentBar;
-		self.dispatch(message)
 	}
```
Comment (Keavon) [inline frontend/wasm/src/api.rs:498]: @mfish33 this didn't seem to be doing anything so far as I could tell. But perhaps I missed something and caused a regression by deleting it?

File: editor/src/document/utility_types.rs [hunk 2]
```diff
@@ -32,3 +32,30 @@ pub enum TargetDocument {
...
 }
+
+#[derive(PartialEq, Clone, Copy, Debug, Serialize, Deserialize)]
+pub enum DocumentMode {
+	DesignMode,
+	SelectMode,
+	GuideMode,
+}
+
+impl ToString for DocumentMode {
```
Comment (0HyperCube) [inline editor/src/document/utility_types.rs:43]: Rust docs state:
> ToString shouldn't be implemented directly: Display should be implemented instead, and you get the ToString implementation for free.

File: editor/src/layout/widgets.rs [hunk 3]
```diff
@@ -170,7 +188,7 @@ pub enum Widget {
 #[derive(Clone, Serialize, Deserialize, Derivative)]
 #[derivative(Debug, PartialEq, Default)]
 pub struct NumberInput {
-	pub value: f64,
+	pub value: Option<f64>,
```
Comment (0HyperCube) [inline editor/src/layout/widgets.rs:191]: Why should this be an option? We appear to just unwrap it in most cases anyway.

File: editor/src/viewport_tools/tool.rs [hunk 4]
```diff
@@ -65,6 +66,53 @@ impl ToolData {
...
+
+	fn register_properties(&self, responses: &mut VecDeque<Message>, layout_target: LayoutTarget) {
+		responses.push_back(
+			LayoutMessage::SendLayout {
+				layout: self.properties(),
+				layout_target,
+			}
+			.into(),
+		)
+	}
```
Comment (0HyperCube) [inline editor/src/viewport_tools/tool.rs:113]: This doesn't need to be implemented manually (as it is the same as the default implementation)

File: frontend/wasm/src/api.rs [hunk 5]
```diff
@@ -552,16 +488,13 @@ impl JsEditorHandle {
...
 
-	/// Creates an empty folder at the document root
-	pub fn create_empty_folder(&self) {
-		let message = DocumentMessage::CreateEmptyFolder { container_path: vec![] };
+	// TODO: Replace with initialization system, issue #524
+	pub fn init_app(&self) {
+		// Switch away from, and back to, the Select Tool to make it display the correct hints in the status bar
+		let message = ToolMessage::ActivateTool { tool_type: ToolType::Path };
+		self.dispatch(message);
+		let message = ToolMessage::ActivateTool { tool_type: ToolType::Select };
```
Comment (0HyperCube) [inline frontend/wasm/src/api.rs:499]: Can we not use `ToolMessage::UpdateHints` directly?

File: frontend/wasm/src/api.rs [hunk 6]
```diff
@@ -591,17 +525,24 @@ pub fn intentional_panic() {
...
 pub fn file_save_suffix() -> String {
 	FILE_SAVE_SUFFIX.into()
 }
 
-/// Get the constant FILE_SAVE_SUFFIX
+/// Get the constant `FILE_SAVE_SUFFIX`
 #[wasm_bindgen]
 pub fn graphite_version() -> String {
 	GRAPHITE_DOCUMENT_VERSION.to_string()
 }
```
Comment (0HyperCube) [inline frontend/wasm/src/api.rs:547]: Comment is incorrect.

File: editor/src/layout/widgets.rs (hunk 3 above)
Comment (Keavon) [reply editor/src/layout/widgets.rs:191]: `None` equates to a dash in the NumberInput GUI.

File: frontend/wasm/src/api.rs (hunk 5 above)
Comment (Keavon) [reply frontend/wasm/src/api.rs]: Comment was out of date, the real issue is tool initialization. I've updated the comment like so:

> // Switch away from, and back to, the Select tool to make it initialize the active tool correctly
> // TODO: Fix the root cause of this issue to avoid this hacky workaround

If you have any ideas for a quick fix, that'd be great. Or we can leave it as is for now and deal with the TODO eventually.

File: editor/src/document/utility_types.rs (hunk 2 above)
Comment (Keavon) [reply editor/src/document/utility_types.rs:43]: Thanks for letting me know!

**Comment by Keavon** [comment]
And @0HyperCube are we good to merge now, or any other changes you noticed or you'd like to poke into closer?

File: frontend/src/dispatcher/js-messages.ts [hunk 7]
```diff
@@ -320,19 +293,11 @@ export class UpdateImageData extends JsMessage {
...
-	readonly factor!: number;
-}
-
-export class UpdateCanvasRotation extends JsMessage {
-	readonly angle_radians!: number;
-}
-
 export type BlendMode =
 	| "Normal"
 	| "Multiply"
```
Comment (Keavon) [inline frontend/src/dispatcher/js-messages.ts:303]: I don't think we actually need this definition on the frontend. Or in other words, `LayerPanelEntry` doesn't need a lot of its metadata like `blend_mode` and `opacity`. Should we just `#[serde(skip)]` these and remove them from `js-messages.ts`? @0HyperCube

Comment (0HyperCube) [reply frontend/src/dispatcher/js-messages.ts:303]: Sure

**Review by 0HyperCube — APPROVED** [review]
Looks good 👍🏽
